/**
 * THE DESIGN ORDER'S OWNER COPY, in one place — the walk's question bank pattern
 * (walk-copy.ts), applied to the graphic configurator so the two flows speak identically.
 *
 * Same rules, same lint (scripts/sim/design-pricing.ts pins them here too):
 *   W1  titles are something an owner would say across the counter: 8 words or fewer
 *   W3  subs say what the answer changes
 *   W4  no em or en dashes anywhere in owner copy
 *   W5  optional questions say out loud what happens if skipped
 *
 * Where the SAME question exists in both flows, the line is imported from walk-copy and used
 * verbatim (never re-worded): uniformity is a build rule, not a style preference.
 *
 * `{tokens}` are substituted by the screen via the walk's own fill().
 */

import { WALK_SUBS, fill } from '../campaigns/data/walk-copy'

export { fill }

export const DESIGN_TITLES: Record<string, string> = {
  job: 'What are we making?',
  where: 'Where will this go?',
  say: 'What should it say?',
  photos: 'Which photos should we use?',
  when: 'When do you need it?',
  'when.event': 'When do you need it in hand?',
  review: 'Look right?',
}

export const DESIGN_SUBS: Record<string, string> = {
  job: 'Say it in a sentence. We handle the rest.',
  where: 'Tap every spot you need. We cut the right size for each one. Your first spot is included.',
  say: 'Watch it take shape. Tap a suggestion or write your own.',
  /* The walk's assets line, verbatim: the promise is the same promise. */
  photos: WALK_SUBS.assets,
  when: 'Standard turnaround delivers by {date}.',
  'when.event': 'Your event is {date}. The design should be working before that.',
  review: "This exact order becomes the designer's brief.",
}

/** Card labels, follow-ups, notes: the small print, same register as WALK_LINES. */
export const DESIGN_LINES: Record<string, string> = {
  'banner.testprices': 'Test prices. The real rate card is not set yet, so these numbers are placeholders.',
  'read.prefix': 'From what you wrote:',
  'read.unplaced': 'We cannot make {list} here yet, so it is not in this order. Message us and we will sort it out.',
  'read.ownphotos': 'Your own photos',
  'print.qty': 'How many of each?',
  'print.client.label': 'My print shop prints it',
  'print.client.sub': 'We hand you print-ready files',
  'print.us.label': 'Handle the printing for me',
  'print.us.sub': 'We run the job. Printing is billed at cost, and you see the receipt.',
  'say.headline': 'The headline',
  'say.question': 'The question',
  'say.title': 'The title',
  'say.whichstory': 'Which story are we telling?',
  'say.wewrite': 'Answer in your own words. We write and polish the final copy, and you approve it before design starts.',
  'say.mode.advanced': 'Advanced: write the exact words yourself',
  'say.mode.guided': 'Back to the guided questions',
  'say.exact': 'The exact copy',
  'say.exact.ph': 'Write it exactly as it should appear on the graphic',
  'say.answer.ph': 'Type your answer',
  'say.like': 'Like',
  'fmt.multi': 'Carousel · {n} pages',
  'fmt.single': 'Single graphic · one page',
  'fmt.how': 'How should it be built?',
  'fmt.single.name': 'Single graphic',
  'fmt.multi.name': 'Carousel',
  'fmt.single.sub': 'One page. Best for one clear message.',
  'fmt.multi.sub': 'Pages people swipe through. Best for stories and lists.',
  'fmt.rec': 'Recommended',
  'xp.order': 'Your order',
  'xp.row.build': 'Format',
  'xp.row.where': 'Where',
  'xp.row.photos': 'Photos',
  'xp.row.when': 'Ready by',
  'xp.row.maker': 'Made by',
  'xp.pages': 'pages',
  'xp.none': 'Pick sizes',
  'xp.standard': 'standard',
  'xp.morequestions': 'Answer {n} more questions. Better answers, better post.',
  'xp.review': 'Review order · ${total}',
  'xp.tosorder': 'Build my order',
  'xp.editstory': 'Edit the story',
  'xp.order.sub': 'Built from your story. Tap anything to change it.',
  'xp.needwords': 'Answer the question above first.',
  'xp.done': 'Done, back to the order',
  'fu.title': 'While we get started',
  'fu.sub': 'A minute on these makes the post better. Skip them and your designer works with what you gave.',
  'fu.send': 'Send answers',
  'fu.sending': 'Sending',
  'fu.sent': 'Got them. Your designer sees these with the order.',
  'fu.notehead': 'More answers from the owner:',
  'maker.market': 'Or pick your creator',
  'maker.market.sub': 'Local creators from the marketplace, at the same listed price. Ratings come from real delivered work.',
  'maker.view': 'View work',
  'mk.ai': 'AI',
  'mk.ai.sub': 'A free draft from your brand and photos, ready in about a minute.',
  'mk.apnosh': 'Apnosh team',
  'mk.apnosh.sub': 'Our designers make it. Pick how much polish.',
  'mk.creator': 'A creator',
  'mk.creator.sub': 'A local creator from the marketplace makes it.',
  'maker.browse': 'Browse all creators',
  'fmt.chip.carousel': 'Carousel',
  'fmt.chip.either': 'Single or carousel',
  'fmt.chip.single': 'Single graphic',
  'dest.rec': 'We picked where this should live based on what it is. Add or remove anything below.',
  'dest.suggested': 'Suggested',
  'brand.title': 'Your brand',
  'brand.sub': 'So it looks like you without you lifting a finger.',
  'brand.file.label': 'Use my brand on file',
  'brand.file.sub': 'Your logo, colors, and fonts travel with the order.',
  'brand.file.empty': 'Nothing on file yet. The designer matches your existing pages.',
  'brand.custom.label': 'Send something different',
  'brand.custom.sub': 'Skip the kit on file and tell us what to use instead.',
  'brand.custom.ph': 'What should we use, like a new logo or different colors',
  'brand.none.label': 'No brand kit',
  'brand.none.sub': 'The designer has free rein on the look.',
  'brand.strip': 'On file',
  'brand.val.file': 'Your kit on file',
  'brand.val.empty': 'Nothing on file, we match your pages',
  'brand.val.custom': 'You are sending it',
  'brand.val.none': 'Designer free rein',
  'brand.photos.travel': 'Your library, we pick the best',
  'xp.back': 'Back to the order',
  'xp.backshort': 'Back',
  'xp.save': 'Save changes',
  'xp.row.brand': 'Brand',
  'xp.row.extras': 'Extras',
  'xp.extras.none': 'None',
  'xp.extras.picked': 'picked',
  'dest.more': 'More places, print and custom sizes',
  'dest.printgroup': 'Print',
  'dest.somewhere': 'Somewhere else',
  'dest.somewhere.sub': 'stickers, billboards, anything',
  'dest.where': 'Where is it going?',
  'dest.print': 'Print sizes',
  'dest.print.sub': 'Physical pieces, sized and set up for real printing.',
  'xp.row.print': 'Print',
  'xp.print.none': 'None',
  'written.title': 'Written versions',
  'written.sub': 'The same answers, written out as words you can paste. We write them, you approve.',
  'say.youanswer': 'You will answer',
  'say.title.blank': 'Leave it blank and your designer writes one from your story.',
  'say.question.title': 'What are we asking?',
  'say.date': 'The big day',
  'say.date.past': 'When it happened',
  'say.adddeal': 'Add a deal or price',
  'say.details': 'The when and where',
  'say.deal': 'The deal',
  'say.featuring': 'Featuring, from your menu',
  'say.optional': 'optional',
  'say.ideas.btn': 'Not sure yet? Get 3 directions',
  'say.ideas.busy': 'Thinking through your idea',
  'say.ideas.title': 'Pick a direction. Every word stays editable.',
  'say.ideas.feature': 'Feature',
  'say.ideas.error': 'Could not get directions right now. Try again in a moment.',
  'say.menu.all': 'Show all {n}',
  'say.menu.less': 'Show less',
  'say.menu.search.ph': 'Search your menu',
  'say.featuring.other': 'Something else',
  'say.featuring.other.ph': 'Name the dish or special',
  'say.headline.ph': 'Live Music Friday',
  'say.details.ph': 'Friday nights, 8pm till late',
  'say.deal.ph': '20% off pitchers',
  'say.preview.headline': 'Your headline',
  'say.preview.details': 'The when and where',
  'say.caption': 'A rough layout of the words, not the design. Your designer makes it look good.',
  'say.note': 'We design exactly these words. Changes after design starts count as a revision.',
  'dest.other.label': 'Custom size',
  'dest.other.ph': 'What is it for, like a sticker or a billboard',
  'dest.other.note': 'Enter the exact size if you know it. We check it and quote it with the rest.',
  'job.popular': 'Or start from a favorite',
  'job.alltypes': 'All types',
  'job.less': 'Show less',
  'job.making': 'Making',
  'job.swap': 'Swap',
  'job.describe.opt': 'Anything else we should know? Optional.',
  'job.slides.title': 'How long should it run?',
  'job.slides.sub': 'We picked from your story. The designer sets the exact page count inside the band.',
  'focus.build.sub': 'One page, or a story that runs pages.',
  'band.short': 'Short',
  'band.standard': 'Standard',
  'band.long': 'Long',
  'tier.ai.carousel': 'AI drafts do not make carousels yet. A designer builds these today.',
  'dest.custom.w': 'Width',
  'dest.custom.h': 'Height',
  'photos.other.label': 'Something else',
  'photos.other.sub': 'Tell us your idea in your own words',
  'photos.other.ph': 'Like: use the photos on my Instagram',
  'photos.best': 'Your sharpest photos come first. Tap every one that fits.',
  'photos.all': 'Show all {n}',
  'photos.less': 'Show less',
  'photos.search.ph': 'Search your photos',
  'photos.or': 'Or hand the photos to us',
  'photos.shoot.label': 'Book a photo shoot',
  'photos.shoot.sub': 'We shoot the real thing at your place. We set the date with you after this goes in.',
  'photos.none.label': 'No photos. Custom artwork',
  'photos.none.sub': 'Your brand, your colors, and drawn art instead of a photo',
  'photos.source.label': 'Find photos for me. ${price}',
  'photos.source.sub': 'We find or license shots that fit your place',
  'photos.gate': 'Too small to look sharp',
  'photos.sharp': 'Sharp',
  'photos.soft': 'OK for social, soft in print',
  'photos.menu': 'From your menu',
  'photos.empty': 'Nothing in your library is sharp enough to design with. Book a shoot, have us find photos, or go with custom artwork.',
  'when.rushnote': 'You mentioned needing this fast. The first day without a rush charge is {date}.',
  'when.rush.q': '{date} is inside our {days} day rush window. Your call:',
  'when.rush.label': 'Rush it for {date}. +${delta}',
  'when.rush.sub': 'Your job moves to the front. Total becomes ${total}.',
  'when.norush.label': 'No rush. $0 extra',
  'when.norush.sub': 'First standard day is {date}. Total stays ${total}.',
  'when.rushon': 'Rush on for {date}.',
  'when.after': '{picked} is after your {event} event. The design would arrive too late to work. Pick a day before it.',
  'when.suggest': '{date}, three days before your event',
  'when.tag.event': 'Amber days are a rush. Days after your event are off.',
  'when.tag': 'Amber days are a rush. Standard days cost nothing extra.',
  'review.revisions': '{n} revision rounds included. Round {next}+ is billed. A change to the message, offer, or destinations is a new order, not a revision.',
  'board.empty': 'Your graphic takes shape here',
  'board.rush': 'Rush',
  'tag.inhand': 'In hand {date}',
  'tag.event': 'Event {date}',
  'dest.included': 'Included',
  'receipt.fee': 'Service fee',
  'panel.sofar': 'Your price so far',
  'panel.total': 'Total',
  'panel.revisions': 'Includes {n} revision rounds.',
  'nav.back': 'Back',
  'nav.next': 'Next',
  'nav.continue': 'Continue',
  'nav.reading': 'Reading your words',
  'photos.upload': 'Upload',
  'done.stamp': 'Ordered',
  'done.title': 'Order recorded',
  'done.sub': 'This exact order becomes the brief your designer works from. Nothing gets re-interpreted.',
  'done.testmode': 'Test mode: no payment was taken.',

  /* The cart: Add to cart then Confirm order (owner call 2026-08-09; the seal is retired). */
  'sum.job': 'The job',
  'sum.featuring': 'Featuring',
  'sum.words': 'The words',
  'sum.where': 'Sizes',
  'sum.photos': 'The photos',
  'sum.when': 'In hand',
  'sum.assigned': 'Assigned to',
  'sum.assigned.who': 'Your Apnosh creative team',
  'sum.assigned.sub': 'A named designer picks it up within 1 business day. You can follow it in Your requests.',
  'tier.title': 'How should it get made?',
  'tier.ai.label': 'AI makes it now',
  'tier.ai.sub': 'A free draft from your brand and photos, in your approvals in about a minute. A designer can finish it later.',
  'tier.ai.note': 'No charge. The draft lands in your approvals to keep, post, or hand to a designer to polish.',
  'tier.ai.cta': 'Make my free draft',
  'tier.most': 'most owners pick this',
  'tier.basic.label': 'Basic',
  'tier.basic.sub': 'Adapted from a design we already hold for you. 1 revision, 2 days. Only works if we have made for you before.',
  'tier.custom.label': 'Custom',
  'tier.custom.sub': 'Designed fresh on your brand. 2 revisions, 4 days.',
  'tier.works.label': 'The works',
  'tier.works.sub': 'Senior designer. 3 concepts to pick from, 3 revisions, and it becomes a template you keep. 7 days.',
  'cart.valve': 'Most orders never adjust. If yours is unusually big we tell you first, and you can cancel free.',
  'cart.add': 'Add to cart',
  'cart.title': 'Your cart',
  'cart.sub': 'One more look, then confirm. Work starts right away.',
  'cart.confirm': 'Confirm order',
  'cart.confirm.sub': 'Goes on your Apnosh bill. Nothing else to do.',
  'cart.change': 'Change something',
  'cart.another': 'Add another graphic',
  'cart.held': 'Also in your cart',
  'cart.remove': 'Remove',
  'cart.pieces': 'graphics in this order',
  'done.title.order': 'Order placed',
  'done.sub.order': 'Your team has it and work starts now. Follow progress and talk to us in Your requests.',

  /* Request mode: the same flow while the rate card is unsigned. No numbers appear
   * anywhere; the seal sends a quote request instead of recording an order. */
  'banner.request': 'Prices are listed as you pick. Nothing goes on your bill until you tap Confirm order.',
  'photos.source.label.request': 'Find the photos for me',
  'when.rush.label.request': 'Yes, rush it for {date}',
  'when.rush.sub.request': 'Rush work costs more. Your quote will show the number.',
  'when.norush.sub.request': 'First standard day is {date}.',
  'receipt.request.label': 'What this costs to send',
  'receipt.request.note': 'We read it, then send you a plan and a real price. Work starts only after you say yes.',
  'done.stamp.request': 'Request sent',
  'done.title.request': 'The team has your graphic.',
  'done.sub.request': 'This exact brief goes to a real person. You will get a plan and a price in your inbox. No charge until you say yes.',
  'send.error': 'Could not send. Check your connection and hold the seal again.',
}
