/**
 * Bespoke handoff orchestrator. One button, end-to-end:
 *   1. Create per-client GitHub repo in apnosh org
 *   2. Commit current bespoke html_doc as index.html + vercel.json + README
 *   3. Create Vercel project linked to the repo
 *   4. Trigger first deployment
 *   5. Invite the designer as a GitHub collaborator (push permission)
 *   6. Save handoff state to bespoke_sites
 *
 * GET returns current handoff status for the form.
 * POST runs the full pipeline (idempotent on repo + project, so safe to
 *      re-run, e.g. if the designer changes).
 * PATCH /sync pulls the latest index.html from the repo into a new
 *      bespoke_history entry so we capture what the designer changed.
 */
import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { createAdminClient } from '@/lib/supabase/admin'
import { createOrFetchRepo, putFile, addCollaborator, getFile, getLatestCommit } from '@/lib/handoff/github'
import { createOrFetchProject, triggerDeployment, getLatestDeployment } from '@/lib/handoff/vercel'

export const maxDuration = 120

async function requireAdmin() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: NextResponse.json({ error: 'Not authenticated' }, { status: 401 }) }
  const { data: profile } = await supabase
    .from('profiles')
    .select('role')
    .eq('id', user.id)
    .maybeSingle()
  if (profile?.role !== 'admin') {
    return { error: NextResponse.json({ error: 'Admin access required' }, { status: 403 }) }
  }
  return { user }
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'site'
}

const VERCEL_JSON = JSON.stringify({
  // Static-site config: serve index.html as the root.
  cleanUrls: true,
  trailingSlash: false,
}, null, 2)

function readmeFor(clientName: string, repoFullName: string, deploymentUrl: string | null): string {
  const codespacesUrl = `https://codespaces.new/${repoFullName}?quickstart=1`
  return `# ${clientName} — bespoke website

Custom HTML + CSS site for **${clientName}**, generated by Apnosh and handed off for designer polish.

## Get started in 30 seconds

Pick whichever feels natural to you:

### Option 1 — Edit in the browser (zero setup)

[![Open in GitHub Codespaces](https://github.com/codespaces/badge.svg)](${codespacesUrl})

Click the button above and you'll get a full VS Code editor in your browser, repo already cloned, GitHub Copilot active. Edit \`index.html\`, commit, and push from the built-in terminal or source-control panel. Vercel deploys automatically within 30 seconds.

### Option 2 — Edit locally (Cursor / VS Code / Claude Code)

\`\`\`bash
git clone https://github.com/${repoFullName}.git
cd ${repoFullName.split('/')[1]}
open index.html  # macOS — see it render in any browser
\`\`\`

Edit \`index.html\` in your editor. Commit and push to \`main\`. That's it.

${deploymentUrl ? `**Live preview:** ${deploymentUrl}\n` : ''}
## What you're working with

- **Single file** — \`index.html\` is fully self-contained: HTML markup + inline \`<style>\` block. No build step, no framework.
- **\`vercel.json\`** — static-site config; don't touch unless you know why.
- **No JavaScript** by default. Add a \`<script>\` block inline if you need interactivity.

## Editing rules (please follow)

- **Preserve \`data-section="..."\` attributes** on top-level sections (\`hero\`, \`about\`, \`offerings\`, \`locations\`, etc.). Apnosh uses them to regenerate individual sections with AI without touching your other edits.
- **Brand colors + voice** are anchored in the client's onboarding profile. The Apnosh team has the original brief — ask if you're unsure whether a change is on-brand.
- **Real photography:** if you swap in real photos, host them on a CDN (Cloudinary, ImageKit, or the client's own S3) and reference by URL. Don't commit binary images to this repo.
- **Test responsively:** open the live preview URL on phone-width before declaring done.

## Workflow

1. Make changes locally or in Codespaces.
2. \`git commit -m "Tighten hero copy"\` (any commit message — be descriptive for your own future reference).
3. \`git push\`.
4. Wait ~30 seconds, refresh ${deploymentUrl || 'the live preview URL'}.
5. Share the live URL with the Apnosh AM for review.

When the AM approves, they'll click "Pull designer's edits back" in the Apnosh admin to import your final HTML into the platform's history (so future AI generations for similar clients can learn from your fixes).

## Questions

Ping the Apnosh AM on whatever channel you use. They have full context on the client's brand, the original brief, and the bespoke generation history.

---

Generated and managed by [Apnosh](https://apnosh.com).
`
}

// ----- GET: status -----
export async function GET(req: NextRequest) {
  const auth = await requireAdmin()
  if (auth.error) return auth.error
  const clientId = req.nextUrl.searchParams.get('clientId')
  if (!clientId) return NextResponse.json({ error: 'clientId required' }, { status: 400 })

  const admin = createAdminClient()
  const { data: site } = await admin
    .from('bespoke_sites')
    .select('github_repo_full_name, github_repo_url, vercel_project_id, vercel_project_name, vercel_deployment_url, designer_email, designer_github_username, handed_off_at, handoff_synced_at')
    .eq('client_id', clientId)
    .maybeSingle()

  if (!site?.handed_off_at) {
    return NextResponse.json({ handedOff: false })
  }

  // If we have a project id, fetch latest deployment + commit live
  let latestDeployment: Awaited<ReturnType<typeof getLatestDeployment>> = null
  let latestCommit: Awaited<ReturnType<typeof getLatestCommit>> = null
  try {
    if (site.vercel_project_id) {
      latestDeployment = await getLatestDeployment(site.vercel_project_id)
    }
    if (site.github_repo_full_name) {
      latestCommit = await getLatestCommit(site.github_repo_full_name, 'main')
    }
  } catch {
    // Silent — return cached state
  }

  return NextResponse.json({
    handedOff: true,
    repoFullName: site.github_repo_full_name,
    repoUrl: site.github_repo_url,
    deploymentUrl: latestDeployment?.url || site.vercel_deployment_url,
    deploymentReadyState: latestDeployment?.readyState ?? null,
    designerEmail: site.designer_email,
    designerGithubUsername: site.designer_github_username,
    handedOffAt: site.handed_off_at,
    syncedAt: site.handoff_synced_at,
    latestCommit,
  })
}

// ----- POST: run handoff pipeline -----
interface HandoffRequest {
  clientId: string
  designerEmail: string
  designerGithubUsername: string
  /** Optional override for the repo slug. Defaults to the client slug. */
  repoSlugOverride?: string
}

export async function POST(req: NextRequest) {
  const auth = await requireAdmin()
  if (auth.error) return auth.error

  const body = await req.json().catch(() => null) as HandoffRequest | null
  if (!body?.clientId || !body.designerEmail || !body.designerGithubUsername) {
    return NextResponse.json({ error: 'clientId, designerEmail, designerGithubUsername required' }, { status: 400 })
  }

  const admin = createAdminClient()
  const { data: site } = await admin
    .from('bespoke_sites')
    .select('html_doc, version')
    .eq('client_id', body.clientId)
    .maybeSingle()
  if (!site?.html_doc) {
    return NextResponse.json({ error: 'No bespoke site exists for this client. Generate one first.' }, { status: 404 })
  }

  const { data: client } = await admin
    .from('clients')
    .select('name, slug')
    .eq('id', body.clientId)
    .maybeSingle()
  if (!client) {
    return NextResponse.json({ error: 'Client not found' }, { status: 404 })
  }

  const repoSlug = body.repoSlugOverride?.trim() || slugify(client.slug || client.name || 'site')

  const events: { event_type: string; payload: Record<string, unknown> }[] = []
  const logEvent = (event_type: string, payload: Record<string, unknown> = {}) => {
    events.push({ event_type, payload })
  }

  try {
    // 1. Create or fetch the repo. auto_init=true means the repo starts
    //    with just a default README, no other files yet.
    const repo = await createOrFetchRepo(
      repoSlug,
      `${client.name} — bespoke website (managed by Apnosh)`,
    )
    logEvent('repo_ready', { fullName: repo.fullName, alreadyExisted: repo.alreadyExisted })

    // 2. Create the Vercel project linked to the (mostly empty) repo
    //    FIRST. This is critical: when Vercel creates the project, it
    //    installs its webhook on the GitHub repo. Any commits made
    //    AFTER this point will fire the webhook and auto-deploy. If
    //    we pushed files first, those commits would land before the
    //    webhook is installed and never trigger a deploy.
    const project = await createOrFetchProject({
      name: repoSlug,
      repoFullName: repo.fullName,
      framework: null,
    })
    logEvent('vercel_project_ready', { id: project.id, alreadyExisted: project.alreadyExisted })

    // 3. NOW push the three files. Each commit fires the webhook, but
    //    Vercel coalesces concurrent deploys, so the final state lands
    //    in production within ~30s.
    const indexCommit = await putFile({
      repoFullName: repo.fullName,
      path: 'index.html',
      content: site.html_doc,
      message: `Sync bespoke site v${site.version} from Apnosh`,
      branch: repo.defaultBranch,
    })
    await putFile({
      repoFullName: repo.fullName,
      path: 'vercel.json',
      content: VERCEL_JSON,
      message: 'Add vercel.json',
      branch: repo.defaultBranch,
    })
    await putFile({
      repoFullName: repo.fullName,
      path: 'README.md',
      content: readmeFor(client.name, repo.fullName, null),
      message: 'Update README for designer handoff',
      branch: repo.defaultBranch,
    })
    logEvent('files_committed', { sha: indexCommit.commitSha, version: site.version })

    // 4. Belt-and-suspenders: also explicitly trigger a deployment via
    //    Vercel's API. If this fails (it sometimes does for fresh
    //    git-linked projects), the webhook above will catch it.
    let deploymentUrl: string | null = null
    try {
      const dep = await triggerDeployment({
        projectName: project.name,
        repoFullName: repo.fullName,
        branch: repo.defaultBranch,
        commitSha: indexCommit.commitSha,
      })
      deploymentUrl = dep.url
      logEvent('deployment_triggered', { id: dep.id, url: dep.url, readyState: dep.readyState })
    } catch (e) {
      logEvent('deployment_trigger_warning', { error: e instanceof Error ? e.message : String(e) })
    }

    // 5. Add designer as collaborator
    try {
      await addCollaborator({
        repoFullName: repo.fullName,
        username: body.designerGithubUsername,
        permission: 'push',
      })
      logEvent('collaborator_invited', { username: body.designerGithubUsername })
    } catch (e) {
      logEvent('collaborator_invite_failed', { error: e instanceof Error ? e.message : String(e) })
      // Continue anyway — the AM can re-add manually
    }

    // 6. Persist handoff state
    const { error: updErr } = await admin
      .from('bespoke_sites')
      .update({
        github_repo_full_name: repo.fullName,
        github_repo_url: repo.htmlUrl,
        vercel_project_id: project.id,
        vercel_project_name: project.name,
        vercel_deployment_url: deploymentUrl,
        designer_email: body.designerEmail,
        designer_github_username: body.designerGithubUsername,
        handed_off_at: new Date().toISOString(),
      })
      .eq('client_id', body.clientId)
    if (updErr) throw new Error(`DB update failed: ${updErr.message}`)

    // 7. Log all events
    if (events.length) {
      await admin.from('bespoke_handoff_events').insert(
        events.map(e => ({
          client_id: body.clientId,
          event_type: e.event_type,
          payload: e.payload,
          created_by: auth.user.id,
        })),
      )
    }

    return NextResponse.json({
      success: true,
      repoFullName: repo.fullName,
      repoUrl: repo.htmlUrl,
      deploymentUrl,
      vercelProjectId: project.id,
    })
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e)
    await admin.from('bespoke_handoff_events').insert({
      client_id: body.clientId,
      event_type: 'error',
      payload: { message, events },
      created_by: auth.user.id,
    })
    return NextResponse.json({ error: 'Handoff failed', detail: message }, { status: 502 })
  }
}

// ----- PATCH /sync: pull designer's edits back into bespoke_history -----
interface SyncRequest {
  clientId: string
}

export async function PATCH(req: NextRequest) {
  const auth = await requireAdmin()
  if (auth.error) return auth.error
  const body = await req.json().catch(() => null) as SyncRequest | null
  if (!body?.clientId) return NextResponse.json({ error: 'clientId required' }, { status: 400 })

  const admin = createAdminClient()
  const { data: site } = await admin
    .from('bespoke_sites')
    .select('github_repo_full_name, version, handoff_synced_sha')
    .eq('client_id', body.clientId)
    .maybeSingle()

  if (!site?.github_repo_full_name) {
    return NextResponse.json({ error: 'Site has not been handed off yet' }, { status: 404 })
  }

  const file = await getFile({
    repoFullName: site.github_repo_full_name,
    path: 'index.html',
    branch: 'main',
  })
  if (!file) {
    return NextResponse.json({ error: 'index.html not found in repo' }, { status: 404 })
  }
  if (file.sha === site.handoff_synced_sha) {
    return NextResponse.json({ success: true, changed: false })
  }

  const newVersion = (site.version ?? 0) + 1
  const latestCommit = await getLatestCommit(site.github_repo_full_name, 'main')
  const note = latestCommit
    ? `Designer edit synced: ${latestCommit.message.slice(0, 100)} (by ${latestCommit.author})`
    : 'Designer edit synced from GitHub'

  const { error: updErr } = await admin
    .from('bespoke_sites')
    .update({
      html_doc: file.content,
      version: newVersion,
      generated_at: new Date().toISOString(),
      handoff_synced_at: new Date().toISOString(),
      handoff_synced_sha: file.sha,
      notes: note,
    })
    .eq('client_id', body.clientId)
  if (updErr) return NextResponse.json({ error: updErr.message }, { status: 500 })

  await admin.from('bespoke_history').insert({
    client_id: body.clientId,
    html_doc: file.content,
    version: newVersion,
    notes: note,
    generated_by: auth.user.id,
  })

  await admin.from('bespoke_handoff_events').insert({
    client_id: body.clientId,
    event_type: 'synced',
    payload: { sha: file.sha, version: newVersion, commit: latestCommit },
    created_by: auth.user.id,
  })

  return NextResponse.json({ success: true, changed: true, version: newVersion })
}
