'use client'

/**
 * TodayHero — the morning paper. Replaces the old TodaysBrief on the
 * client dashboard.
 *
 * Three sections, in order:
 *   1. Headline + AI narrative paragraph (the lead)
 *   2. Needs you today (1-3 urgent actions, click-through)
 *   3. This week (what the strategist + AI are shipping for the client)
 *
 * Stage-aware:
 *   - 'new'        -> emphasis on setting up the data behind active goals
 *   - 'active'     -> emphasis on urgent actions + this-week proof
 *   - 'caught_up'  -> short hero, focus on progress + what's coming
 *
 * The narrative paragraph is AI-generated by /api/dashboard/brief
 * (cached daily, kicked off on mount if not in the bundle).
 */

import { useEffect, useState } from 'react'
import Link from 'next/link'
import {
  Sparkles, RefreshCw, AlertCircle, MessageSquare, CheckSquare, Plug,
  ListTodo, Calendar, ChevronRight,
} from 'lucide-react'
import type { TodayHeroData, NeedsYouItem } from '@/lib/dashboard/get-today-hero'

interface InitialBrief {
  text: string
  generatedAt: string
  model: string
  cached: boolean
}

export default function TodayHero({
  clientId,
  hero,
  initialBrief,
}: {
  clientId: string
  hero: TodayHeroData | null
  initialBrief: InitialBrief | null | undefined
}) {
  const [brief, setBrief] = useState<InitialBrief | null>(initialBrief ?? null)
  const [refreshing, setRefreshing] = useState(false)

  // Kick off background generation if there's no cached brief yet.
  useEffect(() => {
    if (initialBrief === undefined) return
    setBrief(initialBrief)
    if (initialBrief === null && clientId) {
      void generate(clientId, false).then(setBrief).catch(() => { /* silent */ })
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [clientId, initialBrief])

  async function handleRefresh() {
    setRefreshing(true)
    try {
      const next = await generate(clientId, true)
      if (next) setBrief(next)
    } finally {
      setRefreshing(false)
    }
  }

  if (!hero) {
    return (
      <section className="rounded-2xl p-5 mb-5 bg-white border" style={{ borderColor: 'var(--db-border, #e5e5e5)' }}>
        <div className="animate-pulse space-y-3">
          <div className="h-4 bg-ink-6 rounded w-1/3" />
          <div className="h-3 bg-ink-6 rounded w-full" />
          <div className="h-3 bg-ink-6 rounded w-5/6" />
        </div>
      </section>
    )
  }

  const narrative = brief?.text ?? null

  return (
    <section
      className="rounded-2xl p-5 mb-5 bg-white border"
      style={{ borderColor: 'var(--db-border, #e5e5e5)' }}
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-600" />
          <span className="text-[11px] font-semibold uppercase tracking-widest text-ink-3">
            Today
          </span>
        </div>
        <button
          onClick={handleRefresh}
          disabled={refreshing}
          aria-label="Refresh brief"
          className="text-ink-4 hover:text-ink-2 disabled:opacity-40 transition-colors"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${refreshing ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {/* Headline (always present) */}
      <h2 className="text-lg font-semibold text-ink leading-snug mb-2">
        {hero.headline}
      </h2>

      {/* AI narrative */}
      {narrative ? (
        <p className="text-[14px] text-ink-2 leading-relaxed">
          {narrative}
        </p>
      ) : (
        <p className="text-[13px] italic text-ink-4 leading-relaxed">
          Composing the rest of your brief — about 5 seconds...
        </p>
      )}

      {/* Needs you today */}
      {hero.needsYou.length > 0 && (
        <div className="mt-4 pt-4 border-t border-ink-7">
          <p className="text-[11px] font-semibold uppercase tracking-widest text-ink-3 mb-2">
            Needs you today
          </p>
          <ul className="space-y-1.5">
            {hero.needsYou.map((it, idx) => (
              <li key={idx}>
                <Link
                  href={it.href}
                  className="flex items-start gap-2.5 -mx-2 px-2 py-1.5 rounded-md hover:bg-bg-2 transition-colors"
                >
                  <NeedsYouIcon kind={it.kind} urgency={it.urgency} />
                  <div className="flex-1 min-w-0">
                    <p className={`text-[13px] font-medium ${
                      it.urgency === 'high' ? 'text-rose-700' :
                      it.urgency === 'medium' ? 'text-ink' : 'text-ink-2'
                    }`}>
                      {it.label}
                    </p>
                    {it.detail && (
                      <p className="text-[11px] text-ink-3 mt-0.5 leading-snug">{it.detail}</p>
                    )}
                  </div>
                  <ChevronRight className="w-3.5 h-3.5 text-ink-4 flex-shrink-0 mt-1" />
                </Link>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* This week (proof of motion) */}
      {hero.thisWeek.length > 0 && (
        <div className="mt-4 pt-4 border-t border-ink-7">
          <p className="text-[11px] font-semibold uppercase tracking-widest text-ink-3 mb-2">
            From your team this week
          </p>
          <ul className="space-y-1.5">
            {hero.thisWeek.map((it, idx) => (
              <li key={idx}>
                <Link
                  href={it.href ?? '#'}
                  className="flex items-start gap-2.5 -mx-2 px-2 py-1.5 rounded-md hover:bg-bg-2 transition-colors"
                >
                  <Calendar className="w-3.5 h-3.5 text-ink-4 flex-shrink-0 mt-1" />
                  <div className="flex-1 min-w-0">
                    <p className="text-[13px] text-ink leading-snug">
                      {it.label}
                    </p>
                  </div>
                  {it.status && (
                    <span className="text-[10px] font-semibold uppercase tracking-wider px-1.5 py-0.5 rounded bg-emerald-50 text-emerald-700 flex-shrink-0">
                      {it.status}
                    </span>
                  )}
                </Link>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Footer: brief metadata */}
      {brief && (
        <p className="text-[10px] text-ink-4 mt-4">
          Updated {fmtTime(brief.generatedAt)} · AI assistant
        </p>
      )}
    </section>
  )
}

function NeedsYouIcon({ kind, urgency }: { kind?: NeedsYouItem['kind']; urgency: NeedsYouItem['urgency'] }) {
  const cls =
    urgency === 'high' ? 'text-rose-700' :
    urgency === 'medium' ? 'text-amber-700' : 'text-ink-4'
  const Icon =
    kind === 'review' ? MessageSquare :
    kind === 'approval' ? CheckSquare :
    kind === 'connection' ? Plug :
    kind === 'task' ? ListTodo :
    AlertCircle
  return <Icon className={`w-3.5 h-3.5 ${cls} flex-shrink-0 mt-1`} />
}

function fmtTime(iso: string): string {
  return new Date(iso).toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' })
}

async function generate(clientId: string, refresh: boolean): Promise<InitialBrief | null> {
  const res = await fetch('/api/dashboard/brief', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ clientId, refresh }),
  })
  if (!res.ok) return null
  return res.json()
}
