/* DEV codegen: service -> representative {atom,type}, by resolving each service's first
 * classified atomic string against the atomic-catalog `from` index. Lossless because every
 * classification atomic string is a `from` entry (proven by atomicCoverage). Prints the
 * generated TS to stdout. */
import { readFileSync } from 'node:fs'
import { ATOMIC_ACTIONS } from '../src/lib/campaigns/data/atomic-catalog'

const SVC_ATOMICS = JSON.parse(
  readFileSync('/private/tmp/claude-501/-Users-mjbutler35-Documents-GitHub-ApnoshTest--claude-worktrees-objective-lehmann/34720097-f579-4031-8892-9622f2f531bf/scratchpad/svc_atomics.json', 'utf8'),
) as Record<string, string[]>

const fromIndex = new Map<string, { atom: string; type: string }>()
for (const a of ATOMIC_ACTIONS) for (const t of a.types) for (const s of t.from) {
  if (!fromIndex.has(s)) fromIndex.set(s, { atom: a.id, type: t.id })
}

const map: Record<string, { atom: string; type: string }> = {}
const unresolved: string[] = []
for (const [svc, atomics] of Object.entries(SVC_ATOMICS)) {
  const repr = (atomics ?? []).find((s) => fromIndex.has(s))
  if (!repr) { unresolved.push(svc); continue }
  map[svc] = fromIndex.get(repr)!
}

if (unresolved.length) { console.error('UNRESOLVED:', unresolved); process.exit(1) }

const lines = Object.entries(map)
  .map(([svc, r]) => `  '${svc}': { atom: '${r.atom}', type: '${r.type}' },`)
  .join('\n')
console.log(`/* GENERATED by scripts/gen-service-atom-map.ts — do not edit by hand.
 * Maps each catalog service to ONE representative atomic step (its first classified action),
 * the seed used to attach goalPlays down onto atom step-types. ${Object.keys(map).length} services. */
export const SERVICE_PRIMARY_ATOM: Record<string, { atom: string; type: string }> = {
${lines}
}
`)