/**
 * The DB row shape for catalog_services, and the LOSSLESS map between a PricedService and a row.
 * This is the contract for moving the catalog into Postgres: serviceToRow seeds the table,
 * rowToService rebuilds the exact in-code shape from a row (so the generated snapshot the
 * pure/sync composer reads is byte-for-byte the catalog we have today). The nested bits
 * (prices, goalPlays, fit, pieces, metric) ride as JSONB so the round-trip stays exact and the
 * table stays one clean row per service. plain_name lives on the row (future store/admin field)
 * but is NOT part of PricedService, so it does not affect service parity.
 */
import type { PricedService, PricePoint, GoalPlay, ServiceFit, CatalogSection, Handler } from './priced-catalog'

export type CatalogStatus = 'active' | 'draft' | 'archived' | 'coming_soon'

export interface CatalogRow {
  id: string
  section: string
  name: string
  plain_name: string | null
  description: string
  essential: boolean
  handler: string
  handler_why: string
  evidence: string | null
  compliance: string | null
  metric: { label: string; expect: string } | null
  prices: PricePoint[]
  goal_plays: GoalPlay[] | null
  fit: ServiceFit | null
  pieces: { label: string; qty: number }[] | null
  deliverables: { summary: string; included: string[] } | null
  status: CatalogStatus
  sort_order: number
}

/** A PricedService (its runtime form, with goalPlays already attached) -> a DB row. */
export function serviceToRow(s: PricedService, sortOrder: number, plainName?: string): CatalogRow {
  return {
    id: s.id,
    section: s.section,
    name: s.name,
    plain_name: plainName ?? null,
    description: s.desc,
    essential: s.essential,
    handler: s.handler,
    handler_why: s.handlerWhy,
    evidence: s.evidence ?? null,
    compliance: s.compliance ?? null,
    metric: s.metric ?? null,
    prices: s.prices,
    goal_plays: s.goalPlays ?? null,
    fit: s.fit ?? null,
    pieces: s.pieces ?? null,
    deliverables: s.deliverables ?? null,
    status: 'active',
    sort_order: sortOrder,
  }
}

/** Render the generated snapshot file content from services. Shared by scripts/gen-catalog.ts and
 *  the admin Publish action so both produce a byte-identical catalog.generated.ts. */
export function renderGeneratedSnapshot(services: PricedService[]): string {
  return `/* AUTOGENERATED from the catalog_services table. DO NOT EDIT BY HAND.
 * Regenerate with \`npx tsx scripts/gen-catalog.ts\` or the admin Publish button. ${services.length} active services. */
/* eslint-disable */
import type { PricedService } from './priced-catalog'

export const GENERATED_CATALOG: PricedService[] = ${JSON.stringify(services, null, 2)}
`
}

/** A DB row -> the exact PricedService. Optional fields are added back ONLY when present, so the
 *  rebuilt object has the same keys as the original (no `field: undefined` noise). */
export function rowToService(row: CatalogRow): PricedService {
  const s: PricedService = {
    id: row.id,
    section: row.section as CatalogSection,
    name: row.name,
    desc: row.description,
    essential: row.essential,
    handler: row.handler as Handler,
    handlerWhy: row.handler_why,
    prices: row.prices,
  }
  if (row.evidence != null) s.evidence = row.evidence
  if (row.compliance != null) s.compliance = row.compliance
  if (row.metric != null) s.metric = row.metric
  if (row.goal_plays != null) s.goalPlays = row.goal_plays
  if (row.fit != null) s.fit = row.fit
  if (row.pieces != null) s.pieces = row.pieces
  if (row.deliverables != null) s.deliverables = row.deliverables
  return s
}
