/**
 * SERVICE_CHANNELS — the platforms each catalog service actually touches, so the plan can show
 * "Reels, posted to Instagram + TikTok" exhaustively (the campaign builder reads this; it falls back
 * to scanning the service's plain-English deliverables only when an id is missing here).
 *
 * This is a small HAND-AUTHORED side-map, NOT in catalog.generated.ts (that file is autogenerated from
 * the catalog_services table and must not be edited). Keyed by serviceId. An empty array is deliberate:
 * setup/backend services (tracking, CRM, brand kit, offer/menu engineering, reporting) post nowhere,
 * so they correctly show no channel chips. Owner-reviewable — adjust any list to taste.
 *
 * Channel labels are owner-facing: Instagram, TikTok, Facebook, Google, Yelp, TripAdvisor, Apple Maps,
 * Email, Text, Website, Delivery apps, Nextdoor, Phone, Press, In person, In store.
 */
export const SERVICE_CHANNELS: Record<string, string[]> = {
  // ── Foundations / setup (mostly backend → no public channel) ──
  'gbp-setup': ['Google'],
  'review-claim': ['Google', 'Yelp', 'TripAdvisor'],
  'site-menu': ['Website'],
  'website-care': ['Website'],
  'tracking': [],
  'crm-list': [],
  'email-found': ['Email'],
  'sms-found': ['Text'],
  'brand-kit': [],
  'channel-connect': ['Instagram', 'Facebook', 'Google'],
  'listings-sync': ['Google', 'Yelp', 'Facebook', 'Apple Maps'],
  'photo-library': ['Instagram', 'Google', 'Website', 'Delivery apps'],
  'ordering-setup': ['Website', 'Google'],
  // ── Get discovered ──
  'video-engine': ['Instagram', 'Facebook'],
  'video-single': ['Instagram', 'Facebook'],
  'social-mgmt': ['Instagram', 'Facebook'],
  'gbp-posts': ['Google'],
  'local-seo': ['Google', 'Website'],
  'delivery-opt': ['Delivery apps'],
  'paid-ads': ['Google', 'Instagram', 'Facebook'],
  'creator-collab': ['Instagram'],
  'creator-monthly': ['Instagram'],
  'nextdoor-local': ['Nextdoor', 'Facebook'],
  'street-sampling': ['In person'],
  'cross-promo': ['In person'],
  'pr-media': ['Press'],
  'truck-location': ['Instagram', 'Website', 'Text'],
  'graphic': ['Instagram', 'Facebook'],
  'gbp-event-post': ['Google'],
  'fb-event': ['Facebook'],
  // ── Capture / convert ──
  'capture-kit': ['In store'],
  'landing-page': ['Website'],
  'incentive-design': [],
  'ai-phone': ['Phone', 'Text'],
  'pre-opening': ['Google', 'Instagram', 'Email'],
  'welcome-seq': ['Email', 'Text'],
  'second-visit': ['Email', 'Text'],
  'newsletter': ['Email'],
  'sms-program': ['Text'],
  'offer-eng': [],
  'menu-eng': [],
  // ── Events / occasions ──
  'event-pkg': ['Instagram', 'Google', 'Email', 'Text'],
  'bar-events': ['Instagram', 'Google', 'Email'],
  'catering-engine': ['Website', 'Email', 'Google'],
  'giftcards': ['Email', 'Instagram', 'Website'],
  'reservation-protect': ['Text', 'Email'],
  'reminder-send': ['Email', 'Text'],
  'lto-launch': ['Instagram', 'Google', 'Email'],
  'happy-hour-engine': ['Instagram', 'Google', 'Email'],
  'seasonal-cal': [],
  // ── Reviews / reputation ──
  'review-engine': ['Google', 'Yelp'],
  'feedback-loop': ['Email', 'Text'],
  'review-responses': ['Google', 'Yelp'],
  'staff-advocacy': ['Instagram', 'Facebook'],
  'ugc-rights': ['Instagram', 'Facebook'],
  'menu-photo-refresh': ['Instagram', 'Google', 'Website', 'Delivery apps'],
  // ── Retention / loyalty ──
  'loyalty': ['Email', 'Text'],
  'winback': ['Email', 'Text'],
  'referral': ['Email', 'Text'],
  'friend-hook': ['Text', 'Email'],
  'birthday': ['Email', 'Text'],
  'vip-comms': ['Email', 'Text'],
  'concierge': ['In person'],
  // ── Measurement (backend → none) ──
  'reporting': [],
  'google-food-order': ['Google'],
}
