/**
 * SERVICE_TURNAROUND — how long each catalog service takes, so the campaign builder can quote an
 * honest "live in about X" estimate BEFORE the owner ships. OWNER-REVIEWABLE: these become a delivery
 * promise to the restaurant, so they are hand-authored (like prices + volume rates), not computed
 * from labor hours (hours are concurrent work, not calendar turnaround — the real clock is dominated
 * by shoot scheduling, owner approval, and external gates like Google verification).
 *
 * Hand-authored side-map keyed by serviceId — NOT in catalog.generated.ts (autogenerated from the DB,
 * would be overwritten). Same pattern as [[service-channels]] / volume-rates. All durations are in
 * BUSINESS DAYS (the unit owners feel). Three classes:
 *   - setup     one-time, a fixed window; may carry an external GATE (out of Apnosh's hands).
 *   - creative  needs a shoot / drafts / the owner's approval → a min-max range; flag needsShoot.
 *   - recurring runs continuously; the only timeline question is "starts within X", then a cadence.
 *
 * The aggregator (aggregate-golive.ts) reads this to compute a go-live RANGE as a critical PATH
 * (setup + creative run in parallel), never a sum. Edit any number here; owner/ops sign-off pending.
 */

export type TurnaroundGate = {
  kind: 'gbp-verify' | 'listing-propagation' | 'pos-vendor' | 'sms-10dlc' | 'print' | 'external'
  /** extra business days the gate can add, on top of Apnosh's own work window. */
  addDays: { min: number; max: number }
  /** plain owner-facing note naming the dependency. */
  note: string
}

export type ServiceTurnaround =
  | { class: 'setup'; business: { min: number; max: number }; gate?: TurnaroundGate }
  | { class: 'creative'; business: { min: number; max: number }; needsShoot?: boolean; shootLeadDays?: { min: number; max: number } }
  | { class: 'recurring'; startsWithin: { min: number; max: number }; cadence: 'weekly' | 'monthly' | 'continuous' }

const GBP_VERIFY: TurnaroundGate = { kind: 'gbp-verify', addDays: { min: 1, max: 7 }, note: 'Google verifies your profile, which can add a few days.' }
const LISTING_PROP: TurnaroundGate = { kind: 'listing-propagation', addDays: { min: 3, max: 7 }, note: 'Listings can take up to a week to show everywhere.' }
const POS_VENDOR: TurnaroundGate = { kind: 'pos-vendor', addDays: { min: 2, max: 7 }, note: 'Timing depends on your ordering / POS vendor.' }
const SMS_10DLC: TurnaroundGate = { kind: 'sms-10dlc', addDays: { min: 3, max: 14 }, note: 'Carrier registration for texting can take 1-2 weeks.' }
const PRINT: TurnaroundGate = { kind: 'print', addDays: { min: 3, max: 7 }, note: 'Printed cards/QRs are produced and shipped.' }

export const SERVICE_TURNAROUND: Record<string, ServiceTurnaround> = {
  // ── Foundations / setup ──
  'gbp-setup': { class: 'setup', business: { min: 5, max: 7 }, gate: GBP_VERIFY },
  'review-claim': { class: 'setup', business: { min: 3, max: 5 }, gate: LISTING_PROP },
  'site-menu': { class: 'setup', business: { min: 3, max: 5 } },
  'website-care': { class: 'recurring', startsWithin: { min: 2, max: 4 }, cadence: 'continuous' },
  'tracking': { class: 'setup', business: { min: 2, max: 3 } },
  'crm-list': { class: 'setup', business: { min: 2, max: 4 } },
  'email-found': { class: 'setup', business: { min: 2, max: 3 } },
  'sms-found': { class: 'setup', business: { min: 3, max: 5 }, gate: SMS_10DLC },
  'brand-kit': { class: 'setup', business: { min: 7, max: 12 } },
  'channel-connect': { class: 'setup', business: { min: 1, max: 2 } },
  'listings-sync': { class: 'setup', business: { min: 3, max: 5 }, gate: LISTING_PROP },
  'photo-library': { class: 'creative', business: { min: 7, max: 12 }, needsShoot: true, shootLeadDays: { min: 5, max: 10 } },
  'ordering-setup': { class: 'setup', business: { min: 3, max: 7 }, gate: POS_VENDOR },
  // ── Get discovered ──
  'video-engine': { class: 'creative', business: { min: 10, max: 14 }, needsShoot: true, shootLeadDays: { min: 5, max: 10 } },
  'video-single': { class: 'creative', business: { min: 7, max: 12 }, needsShoot: true, shootLeadDays: { min: 5, max: 10 } },
  'social-mgmt': { class: 'recurring', startsWithin: { min: 5, max: 7 }, cadence: 'monthly' },
  'gbp-posts': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'monthly' },
  'local-seo': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'monthly' },
  'delivery-opt': { class: 'setup', business: { min: 5, max: 7 }, gate: POS_VENDOR },
  'paid-ads': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'continuous' },
  'creator-collab': { class: 'creative', business: { min: 8, max: 14 }, needsShoot: true, shootLeadDays: { min: 5, max: 10 } },
  'creator-monthly': { class: 'recurring', startsWithin: { min: 7, max: 14 }, cadence: 'monthly' },
  'nextdoor-local': { class: 'setup', business: { min: 2, max: 4 } },
  'street-sampling': { class: 'setup', business: { min: 5, max: 10 } },
  'cross-promo': { class: 'setup', business: { min: 7, max: 14 } },
  'pr-media': { class: 'creative', business: { min: 14, max: 30 } },
  'truck-location': { class: 'setup', business: { min: 3, max: 5 } },
  'graphic': { class: 'creative', business: { min: 3, max: 5 } },
  'gbp-event-post': { class: 'creative', business: { min: 2, max: 4 } },
  'fb-event': { class: 'creative', business: { min: 2, max: 4 } },
  // ── Capture / convert ──
  'capture-kit': { class: 'setup', business: { min: 3, max: 5 }, gate: PRINT },
  'landing-page': { class: 'setup', business: { min: 3, max: 5 } },
  'incentive-design': { class: 'setup', business: { min: 2, max: 4 } },
  'ai-phone': { class: 'setup', business: { min: 5, max: 7 }, gate: POS_VENDOR },
  'pre-opening': { class: 'setup', business: { min: 7, max: 14 } },
  'welcome-seq': { class: 'setup', business: { min: 3, max: 5 } },
  'second-visit': { class: 'setup', business: { min: 2, max: 4 } },
  'newsletter': { class: 'recurring', startsWithin: { min: 5, max: 7 }, cadence: 'monthly' },
  'sms-program': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'monthly' },
  'offer-eng': { class: 'setup', business: { min: 3, max: 5 } },
  'menu-eng': { class: 'setup', business: { min: 5, max: 7 } },
  // ── Events / occasions ──
  'event-pkg': { class: 'creative', business: { min: 5, max: 10 } },
  'bar-events': { class: 'recurring', startsWithin: { min: 5, max: 7 }, cadence: 'monthly' },
  'catering-engine': { class: 'setup', business: { min: 7, max: 14 } },
  'giftcards': { class: 'setup', business: { min: 5, max: 7 }, gate: POS_VENDOR },
  'reservation-protect': { class: 'setup', business: { min: 3, max: 5 } },
  'reminder-send': { class: 'recurring', startsWithin: { min: 2, max: 3 }, cadence: 'continuous' },
  'lto-launch': { class: 'creative', business: { min: 7, max: 10 } },
  'happy-hour-engine': { class: 'setup', business: { min: 5, max: 7 } },
  'seasonal-cal': { class: 'setup', business: { min: 3, max: 5 } },
  // ── Reviews / reputation ──
  'review-engine': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'continuous' },
  'feedback-loop': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'continuous' },
  'review-responses': { class: 'recurring', startsWithin: { min: 1, max: 2 }, cadence: 'continuous' },
  'staff-advocacy': { class: 'setup', business: { min: 5, max: 7 } },
  'ugc-rights': { class: 'setup', business: { min: 3, max: 5 } },
  'menu-photo-refresh': { class: 'creative', business: { min: 5, max: 10 }, needsShoot: true, shootLeadDays: { min: 5, max: 10 } },
  // ── Retention / loyalty ──
  'loyalty': { class: 'recurring', startsWithin: { min: 5, max: 7 }, cadence: 'continuous' },
  'winback': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'monthly' },
  'referral': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'continuous' },
  'friend-hook': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'continuous' },
  'birthday': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'continuous' },
  'vip-comms': { class: 'recurring', startsWithin: { min: 3, max: 5 }, cadence: 'monthly' },
  'concierge': { class: 'recurring', startsWithin: { min: 5, max: 7 }, cadence: 'continuous' },
  // ── Measurement ──
  'reporting': { class: 'recurring', startsWithin: { min: 5, max: 7 }, cadence: 'monthly' },
  'google-food-order': { class: 'setup', business: { min: 3, max: 7 }, gate: POS_VENDOR },
}

/** Per content-piece-type production window (business days), used for the creative critical path. */
export const CONTENT_TURNAROUND: Record<string, { min: number; max: number; needsShoot: boolean }> = {
  reel: { min: 7, max: 10, needsShoot: true },
  video: { min: 7, max: 10, needsShoot: true },
  photo: { min: 5, max: 7, needsShoot: true },
  story: { min: 2, max: 4, needsShoot: false },
  post: { min: 2, max: 4, needsShoot: false },
  carousel: { min: 3, max: 5, needsShoot: false },
  graphic: { min: 3, max: 5, needsShoot: false },
  email: { min: 1, max: 3, needsShoot: false },
  sms: { min: 1, max: 3, needsShoot: false },
}
const CONTENT_DEFAULT = { min: 3, max: 5, needsShoot: false }

export function contentTurnaround(type: string) {
  return CONTENT_TURNAROUND[type] ?? CONTENT_DEFAULT
}

export function turnaroundFor(serviceId: string): ServiceTurnaround | undefined {
  return SERVICE_TURNAROUND[serviceId]
}

/** Plain-language ETA label derived from the turnaround, replacing the old hardcoded "~1 week". */
export function etaLabelFor(serviceId: string): string {
  const t = SERVICE_TURNAROUND[serviceId]
  if (!t) return '~1 week'
  if (t.class === 'recurring') return `starts in ${t.startsWithin.min}-${t.startsWithin.max} days`
  const b = t.business
  const lo = t.class === 'creative' && t.needsShoot && t.shootLeadDays ? b.min + t.shootLeadDays.min : b.min
  const hi = t.class === 'creative' && t.needsShoot && t.shootLeadDays ? b.max + t.shootLeadDays.max : b.max
  return `${lo}-${hi} days`
}

// Coverage guard (dev only): every catalog service should have a turnaround so the go-live estimate
// never silently treats a service as zero-time. Mirrors the margin-floor warn loop in priced-catalog.
if (process.env.NODE_ENV !== 'production') {
  void (async () => {
    try {
      const { GENERATED_CATALOG } = await import('./catalog.generated')
      for (const s of GENERATED_CATALOG) {
        if (!SERVICE_TURNAROUND[s.id]) console.warn(`[turnaround] missing turnaround for service: ${s.id}`)
      }
    } catch { /* generated catalog not available in this context */ }
  })()
}
