'use client'

/**
 * /dashboard/campaigns/new — the campaign builder.
 *   pick a goal → answer a short spec → review the COMPLETE best-practice plan
 *   (every piece transparent + toggleable) → create.
 * The plan is generated by composePlay (blueprint-driven), so a one-line ask
 * always comes back as the whole play, never a thin list.
 */

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { ChevronLeft, X, ArrowRight, Loader2, Check, Sparkles } from 'lucide-react'
import { useClient } from '@/lib/client-context'
import {
  CAMPAIGN_TEMPLATES, CATEGORY_META, AUDIENCES,
  type CampaignTemplate, type CampaignCategory, type SpecQuestion,
} from '@/lib/campaigns/data/campaign-templates'
import { composePlay } from '@/lib/campaigns/play-engine'
import type { ComposeResult } from '@/lib/campaigns/campaign-composer'
import { playsFrom } from '@/lib/campaigns/plays'
import { summarize, type BuildPath, type CampaignDraft, type LineItem, type OptOutReason } from '@/lib/campaigns/types'
import PlayCard from '@/components/campaigns/play-card'
import LineCard from '@/components/campaigns/line-card'
import HonestBillBar from '@/components/campaigns/honest-bill-bar'
import { C, DISPLAY, GRAD } from '@/components/campaigns/ui'

type Step = 'pick' | 'spec' | 'path' | 'review'
type AiState = 'idle' | 'drafting' | 'done' | 'error'

export default function NewCampaignPage() {
  const router = useRouter()
  const { client } = useClient()
  const [tplId, setTplId] = useState<string | null>(null)
  const [spec, setSpec] = useState<Record<string, string>>({})
  const [step, setStep] = useState<Step>('pick')
  const [path, setPath] = useState<BuildPath>('strategist')
  const [aiState, setAiState] = useState<AiState>('idle')
  const [plan, setPlan] = useState<ComposeResult | null>(null)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const tpl = CAMPAIGN_TEMPLATES.find((t) => t.id === tplId) ?? null

  const pickTemplate = (t: CampaignTemplate) => {
    setTplId(t.id)
    setSpec({ audience: t.defaultAudienceIds.join(',') })
    setStep('spec')
  }

  /** Choose a build path → generate the complete plan, apply path defaults, go to review. */
  function choosePath(p: BuildPath) {
    if (!tpl) return
    setPath(p)
    let built = composePlay(tpl, spec, { has: [] })  // TODO: pass owner's owned-capabilities for auto opt-out
    if (p === 'diy') {
      // "I'll build it myself" — every core piece defaults to DIY ($0). Owner keeps what they want done for them.
      built = { ...built, items: built.items.map((x) => (x.included ? { ...x, optOut: 'diy' as const } : x)) }
    }
    setPlan(built)
    setStep('review')
    if (p === 'ai') void runAiDraft(built)
  }

  /** The "AI builds it" path — a real model call drafts copy for each piece. */
  async function runAiDraft(built: ComposeResult) {
    if (!client?.id) return
    setAiState('drafting')
    try {
      const res = await fetch('/api/campaigns/ai-draft', {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ clientId: client.id, brief: built.brief, items: built.items, businessName: client?.name }),
      })
      if (!res.ok) throw new Error()
      const { drafts } = await res.json() as { drafts: Record<string, { title?: string; body: string }> }
      setPlan((p) => (p ? { ...p, items: p.items.map((x) => (drafts[x.id] ? { ...x, draft: drafts[x.id] } : x)) } : p))
      setAiState('done')
    } catch {
      setAiState('error')
    }
  }

  // ── live plan edits ──────────────────────────────────────────
  const mutate = (fn: (items: LineItem[]) => LineItem[]) => setPlan((p) => (p ? { ...p, items: fn(p.items) } : p))
  const toggleOptOut = (id: string, r: OptOutReason) => mutate((items) => items.map((x) => (x.id === id ? { ...x, optOut: x.optOut === r ? undefined : r } : x)))
  const toggleInclude = (id: string) => mutate((items) => items.map((x) => (x.id === id ? { ...x, included: !x.included, optOut: undefined } : x)))
  // "Remove" = drop from the active plan but keep it re-addable under "Go further".
  const remove = (id: string) => mutate((items) => items.map((x) => (x.id === id ? { ...x, included: false, optOut: undefined } : x)))
  const setQty = (id: string, qty: number) => mutate((items) => items.map((x) => (x.id === id ? { ...x, qty: Math.max(1, qty) } : x)))

  async function create() {
    if (!tpl || !plan || !client?.id) return
    setSaving(true); setError(null)
    const items = plan.items.filter((x) => x.included || x.optOut)  // keep what's in the plan (active, DIY, have-it)
    const s = summarize(items)
    const draft: CampaignDraft = {
      id: 'new', name: plan.name,
      intent: tpl.durationWeeks === null ? 'ongoing' : 'one-off',
      path, phase: path === 'strategist' ? 'review' : 'build',
      budgetMonthly: s.perMonth, items,
      planned: true, goalKey: tpl.goalKey,
      occasion: tpl.id === 'event' ? (spec.what || undefined) : undefined,
      targetDate: spec.when || undefined,
      context: spec.shift || spec.night || undefined,
      brief: plan.brief,
    }
    try {
      const res = await fetch('/api/campaigns', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ clientId: client.id, draft }) })
      if (!res.ok) throw new Error((await res.json().catch(() => ({}))).error || `Save failed (${res.status})`)
      const { id } = await res.json()
      router.push(`/dashboard/campaigns/${id}`)
    } catch (e) {
      setError(e instanceof Error ? e.message : 'Save failed')
      setSaving(false)
    }
  }

  const back = () => {
    if (step === 'review') setStep('path')
    else if (step === 'path') setStep('spec')
    else if (step === 'spec') { setStep('pick'); setTplId(null); setSpec({}) }
    else router.push('/dashboard/campaigns')
  }

  return (
    <div style={{ position: 'fixed', inset: 0, zIndex: 60, background: C.bg, display: 'flex', justifyContent: 'center' }}>
      <div style={{ width: '100%', maxWidth: 480, background: '#fff', display: 'flex', flexDirection: 'column', boxShadow: '0 0 40px rgba(0,0,0,0.06)', height: '100dvh' }}>
        {/* header */}
        <div style={{ flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 16px', borderBottom: `1px solid ${C.line}` }}>
          <button onClick={back} style={hdrBtn}>{step === 'pick' ? <X size={20} color={C.faint} /> : <><ChevronLeft size={18} /> Back</>}</button>
          <StepDots step={step} />
          <button onClick={() => router.push('/dashboard/campaigns')} aria-label="Close" style={{ ...hdrBtn, color: C.faint }}><X size={20} /></button>
        </div>

        <div style={{ flex: 1, minHeight: 0, overflowY: 'auto', padding: step === 'review' ? '16px 16px 28px' : '18px 18px 28px' }}>
          {step === 'pick' && <TemplatePicker onPick={pickTemplate} />}
          {step === 'spec' && tpl && <SpecForm tpl={tpl} spec={spec} setSpec={setSpec} />}
          {step === 'path' && <PathChooser onPick={choosePath} />}
          {step === 'review' && plan && <ReviewCanvas plan={plan} path={path} aiState={aiState} onToggleOptOut={toggleOptOut} onToggleInclude={toggleInclude} onRemove={remove} onSetQty={setQty} />}
        </div>

        {/* footer */}
        {step === 'spec' && tpl && (
          <Footer><button onClick={() => setStep('path')} style={ctaBtn}>Build my plan <ArrowRight size={17} /></button></Footer>
        )}
        {step === 'review' && plan && (
          <>
            <HonestBillBar items={plan.items} note={path === 'strategist' ? 'Approving is free. Each piece bills only when it ships.' : path === 'diy' ? 'Your plan, your hands. Nothing billed for what you do yourself.' : 'Nothing is charged until a piece ships.'} />
            <Footer>
              {error && <div style={{ color: C.red, fontSize: 12.5, marginBottom: 8, textAlign: 'center' }}>{error}</div>}
              {(() => {
                const drafting = path === 'ai' && aiState === 'drafting'
                const blocked = saving || drafting
                return (
                  <button onClick={create} disabled={blocked} style={{ ...ctaBtn, opacity: blocked ? 0.7 : 1 }}>
                    {saving ? <><Loader2 size={17} className="animate-spin" /> Creating…</>
                      : drafting ? <><Loader2 size={17} className="animate-spin" /> Writing your copy…</>
                      : path === 'strategist' ? <>Send to Apnosh <ArrowRight size={17} /></>
                      : path === 'diy' ? <>Save my checklist <ArrowRight size={17} /></>
                      : <>Save &amp; schedule <ArrowRight size={17} /></>}
                  </button>
                )
              })()}
            </Footer>
          </>
        )}
      </div>
    </div>
  )
}

function Footer({ children }: { children: React.ReactNode }) {
  return <div style={{ flexShrink: 0, borderTop: `1px solid ${C.line}`, padding: '12px 18px calc(12px + env(safe-area-inset-bottom))', background: '#fff' }}>{children}</div>
}
const hdrBtn: React.CSSProperties = { display: 'inline-flex', alignItems: 'center', gap: 4, background: 'none', border: 'none', color: C.mute, fontWeight: 600, fontSize: 14, cursor: 'pointer', padding: 4 }
const ctaBtn: React.CSSProperties = { width: '100%', background: GRAD, color: '#fff', border: 'none', borderRadius: 14, padding: 14, fontWeight: 700, fontSize: 15, cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8 }

function StepDots({ step }: { step: Step }) {
  const i = step === 'pick' ? 0 : step === 'spec' ? 1 : step === 'path' ? 2 : 3
  return (
    <div style={{ display: 'flex', gap: 6 }}>
      {[0, 1, 2, 3].map((n) => <span key={n} style={{ width: n === i ? 18 : 6, height: 6, borderRadius: 99, background: n === i ? C.green : C.line, transition: 'all .2s' }} />)}
    </div>
  )
}

/* ── Step 3 · pick a build path ────────────────────────────────── */
const PATHS: { key: BuildPath; icon: string; title: string; blurb: string; cost: string }[] = [
  { key: 'ai', icon: '✨', title: 'Build it for me with AI', blurb: 'AI drafts every piece now — the graphic copy, captions, emails, texts. You tweak and ship today.', cost: 'You pay for what ships' },
  { key: 'diy', icon: '🙋', title: 'I’ll build it myself', blurb: 'Start from the complete plan. Keep what you want done for you, do the rest yourself.', cost: '$0 for what you do yourself' },
  { key: 'strategist', icon: '◆', title: 'Apnosh builds it', blurb: 'Our team builds every piece to your brand. You approve before anything ships.', cost: 'You approve before any charge' },
]
function PathChooser({ onPick }: { onPick: (p: BuildPath) => void }) {
  return (
    <div>
      <h1 style={{ fontFamily: DISPLAY, fontWeight: 600, fontSize: 23, margin: '0 0 4px' }}>Who builds it?</h1>
      <p style={{ fontSize: 13.5, color: C.mute, margin: '0 0 18px' }}>Same complete plan, three ways to get it done. You can change any piece later.</p>
      {PATHS.map((p) => (
        <button key={p.key} onClick={() => onPick(p.key)} style={{ width: '100%', textAlign: 'left', display: 'flex', alignItems: 'flex-start', gap: 13, background: '#fff', border: `1px solid ${C.line}`, borderRadius: 16, padding: '15px 15px', marginBottom: 10, cursor: 'pointer' }}>
          <span style={{ flex: 'none', width: 42, height: 42, borderRadius: 12, display: 'grid', placeItems: 'center', fontSize: 21, background: C.greenSoft }}>{p.icon}</span>
          <span style={{ flex: 1, minWidth: 0 }}>
            <span style={{ display: 'block', fontWeight: 700, fontSize: 15, color: C.ink }}>{p.title}</span>
            <span style={{ display: 'block', fontSize: 12.5, color: C.mute, marginTop: 2, lineHeight: 1.4 }}>{p.blurb}</span>
            <span style={{ display: 'inline-block', fontSize: 11, fontWeight: 600, color: C.greenDk, marginTop: 6 }}>{p.cost}</span>
          </span>
          <ArrowRight size={17} color={C.faint} style={{ flexShrink: 0, marginTop: 4 }} />
        </button>
      ))}
    </div>
  )
}

/* ── Step 1 · pick a goal ──────────────────────────────────────── */
function TemplatePicker({ onPick }: { onPick: (t: CampaignTemplate) => void }) {
  const cats = Object.keys(CATEGORY_META) as CampaignCategory[]
  return (
    <div>
      <h1 style={{ fontFamily: DISPLAY, fontWeight: 600, fontSize: 25, margin: '0 0 4px' }}>What do you want to do?</h1>
      <p style={{ fontSize: 13.5, color: C.mute, margin: '0 0 18px' }}>Pick a goal — we build the whole plan, you keep what you need.</p>
      {cats.map((cat) => {
        const tpls = CAMPAIGN_TEMPLATES.filter((t) => t.category === cat)
        if (!tpls.length) return null
        return (
          <div key={cat} style={{ marginBottom: 18 }}>
            <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '.06em', textTransform: 'uppercase', color: C.faint, marginBottom: 8 }}>{CATEGORY_META[cat].label}</div>
            {tpls.map((t) => (
              <button key={t.id} onClick={() => onPick(t)} style={{ width: '100%', textAlign: 'left', display: 'flex', alignItems: 'center', gap: 12, background: '#fff', border: `1px solid ${C.line}`, borderRadius: 14, padding: '13px 14px', marginBottom: 8, cursor: 'pointer' }}>
                <span style={{ fontSize: 24, flexShrink: 0 }}>{t.icon}</span>
                <span style={{ flex: 1, minWidth: 0 }}>
                  <span style={{ display: 'block', fontWeight: 700, fontSize: 14.5, color: C.ink }}>{t.name}</span>
                  <span style={{ display: 'block', fontSize: 12.5, color: C.mute, marginTop: 1 }}>{t.tagline}</span>
                </span>
                <ArrowRight size={17} color={C.faint} style={{ flexShrink: 0 }} />
              </button>
            ))}
          </div>
        )
      })}
    </div>
  )
}

/* ── Step 2 · short spec ───────────────────────────────────────── */
function SpecForm({ tpl, spec, setSpec }: { tpl: CampaignTemplate; spec: Record<string, string>; setSpec: (s: Record<string, string>) => void }) {
  const set = (k: string, v: string) => setSpec({ ...spec, [k]: v })
  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 16 }}>
        <span style={{ fontSize: 30 }}>{tpl.icon}</span>
        <div>
          <h1 style={{ fontFamily: DISPLAY, fontWeight: 600, fontSize: 21, margin: 0, lineHeight: 1.15 }}>{tpl.name}</h1>
          <div style={{ fontSize: 13, color: C.mute }}>{tpl.objective} · {tpl.durationWeeks ? `${tpl.durationWeeks} weeks` : 'ongoing'}</div>
        </div>
      </div>
      {tpl.questions.map((q) => <Question key={q.id} q={q} tpl={tpl} value={spec[q.id] ?? ''} onChange={(v) => set(q.id, v)} />)}
    </div>
  )
}

/* ── Step 3 · review the complete plan ─────────────────────────── */
function ReviewCanvas({ plan, path, aiState, onToggleOptOut, onToggleInclude, onRemove, onSetQty }: {
  plan: ComposeResult
  path: BuildPath
  aiState: AiState
  onToggleOptOut: (id: string, r: OptOutReason) => void
  onToggleInclude: (id: string) => void
  onRemove: (id: string) => void
  onSetQty: (id: string, qty: number) => void
}) {
  const core = plan.items.filter((i) => i.included)
  const recommended = plan.items.filter((i) => !i.included)
  const plays = playsFrom(core)
  const brief = plan.brief

  return (
    <div>
      <div style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: C.greenSoft, color: C.greenDk, borderRadius: 99, padding: '4px 11px', fontWeight: 700, fontSize: 11, marginBottom: 10 }}>
        <Sparkles size={13} /> Your complete plan
      </div>
      <h1 style={{ fontFamily: DISPLAY, fontWeight: 600, fontSize: 23, margin: '0 0 4px', lineHeight: 1.15 }}>{plan.name}</h1>
      <p style={{ fontSize: 13, color: C.mute, margin: '0 0 6px' }}>{brief.objective}{brief.projected ? ` · ${brief.projected}` : ''}</p>
      <p style={{ fontSize: 12, color: C.faint, margin: '0 0 14px', lineHeight: 1.4 }}>Here’s the whole play a great marketer would run. Keep it all, or tap any piece to do it yourself or skip it — your bill only counts what you keep.</p>

      {path === 'ai' && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, background: '#f4f0ff', border: '1px solid #e6dcff', color: '#6b46c1', borderRadius: 12, padding: '10px 12px', marginBottom: 14, fontSize: 12.5, fontWeight: 600 }}>
          {aiState === 'drafting' && <><Loader2 size={15} className="animate-spin" /> AI is writing your content…</>}
          {aiState === 'done' && <><Sparkles size={15} /> AI drafted your copy — open any piece to read &amp; tweak it.</>}
          {aiState === 'error' && <span style={{ color: C.mute, fontWeight: 500 }}>Couldn’t reach the AI writer — you can still ship and add copy later.</span>}
          {aiState === 'idle' && <><Sparkles size={15} /> AI will draft each piece.</>}
        </div>
      )}
      {path === 'strategist' && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, background: C.greenSoft, color: C.greenDk, borderRadius: 12, padding: '10px 12px', marginBottom: 14, fontSize: 12.5, fontWeight: 600 }}>
          ◆ Apnosh will build every piece you keep. You approve before anything ships.
        </div>
      )}
      {path === 'diy' && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, background: '#f5f5f7', color: C.mute, borderRadius: 12, padding: '10px 12px', marginBottom: 14, fontSize: 12.5, fontWeight: 600 }}>
          🙋 Your checklist. Flip any piece to “done for me” if you’d rather we handle it.
        </div>
      )}

      <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
        {plays.map((p) => (
          <PlayCard key={p.key} play={p} onToggleOptOut={onToggleOptOut} onToggleInclude={onToggleInclude} onRemove={onRemove} onSetQty={onSetQty} />
        ))}
      </div>

      {recommended.length > 0 && (
        <div style={{ marginTop: 20 }}>
          <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '.06em', textTransform: 'uppercase', color: C.faint, marginBottom: 4 }}>Go further</div>
          <p style={{ fontSize: 12, color: C.mute, margin: '0 0 10px' }}>Optional moves that make the play hit harder. Add what fits your budget.</p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {recommended.map((it) => (
              <LineCard key={it.id} item={it} onToggleInclude={() => onToggleInclude(it.id)} />
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

/* ── spec inputs ───────────────────────────────────────────────── */
function Question({ q, tpl, value, onChange }: { q: SpecQuestion; tpl: CampaignTemplate; value: string; onChange: (v: string) => void }) {
  return (
    <div style={{ marginBottom: 16 }}>
      <div style={{ fontSize: 13.5, fontWeight: 600, color: C.ink, marginBottom: 8 }}>{q.prompt}{q.optional && <span style={{ color: C.faint, fontWeight: 400 }}> · optional</span>}</div>
      {q.kind === 'chips' && <Chips options={(q.options ?? []).map((o) => ({ label: o.label, value: o.value }))} value={value} onChange={onChange} allowText={q.allowText} placeholder={q.placeholder} />}
      {q.kind === 'offer' && <Chips options={tpl.suggestedOffers.map((o) => ({ label: o.label, value: o.label, note: o.note }))} value={value} onChange={onChange} allowText placeholder="Or describe your own offer" />}
      {q.kind === 'audience' && <AudiencePicker value={value} onChange={onChange} />}
      {q.kind === 'text' && <input value={value} onChange={(e) => onChange(e.target.value)} placeholder={q.placeholder} style={inputStyle} />}
      {q.kind === 'date' && <input type="date" value={value} onChange={(e) => onChange(e.target.value)} style={inputStyle} />}
    </div>
  )
}

const inputStyle: React.CSSProperties = { width: '100%', border: `1px solid ${C.line}`, borderRadius: 12, padding: '11px 13px', fontSize: 14, color: C.ink, fontFamily: 'inherit', background: '#fff', boxSizing: 'border-box' }

function Chips({ options, value, onChange, allowText, placeholder }: { options: { label: string; value: string; note?: string }[]; value: string; onChange: (v: string) => void; allowText?: boolean; placeholder?: string }) {
  const isPreset = options.some((o) => o.value === value)
  return (
    <div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 7 }}>
        {options.map((o) => {
          const on = value === o.value
          return <button key={o.value} onClick={() => onChange(o.value)} title={o.note} style={{ border: `1px solid ${on ? C.green : C.line}`, background: on ? C.greenSoft : '#fff', color: on ? C.greenDk : C.mute, borderRadius: 999, padding: '7px 13px', fontSize: 13, fontWeight: on ? 700 : 500, cursor: 'pointer' }}>{o.label}</button>
        })}
      </div>
      {allowText && <input value={isPreset ? '' : value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder ?? 'Or type your own'} style={{ ...inputStyle, marginTop: 8 }} />}
    </div>
  )
}

function AudiencePicker({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  const selected = value ? value.split(',').filter(Boolean) : []
  const toggle = (id: string) => {
    const next = selected.includes(id) ? selected.filter((x) => x !== id) : [...selected, id]
    onChange(next.join(','))
  }
  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 7 }}>
      {Object.values(AUDIENCES).map((a) => {
        const on = selected.includes(a.id)
        return (
          <button key={a.id} onClick={() => toggle(a.id)} title={a.sub} style={{ display: 'inline-flex', alignItems: 'center', gap: 5, border: `1px solid ${on ? C.green : C.line}`, background: on ? C.greenSoft : '#fff', color: on ? C.greenDk : C.mute, borderRadius: 999, padding: '7px 12px', fontSize: 13, fontWeight: on ? 700 : 500, cursor: 'pointer' }}>
            <span>{a.icon}</span>{a.label}{on && <Check size={13} />}
          </button>
        )
      })}
    </div>
  )
}
