-- ============================================================
-- Migration 055: Billing System v2
-- ============================================================
-- Moves billing from the early business_id-keyed scaffolding onto the
-- canonical client_id model, per the billing spec.
--
-- Context: the previous `subscriptions` and `invoices` tables were
-- scaffolded in migration 001 + 002 but never collected real Stripe
-- revenue (clients were paying by check). This drops them and replaces
-- with a clean spec-compliant schema keyed on clients.id, using
-- integer-cents money and proper invoice line items.
--
-- What's preserved:
--   * orders table (powers /dashboard/orders self-serve add-ons)
--   * client_billing (contract + payment method mirror)
--   * service_catalog (internal service IDs; used by billing-grants)
--   * work_briefs (generated by the webhook on confirmed orders)
--
-- What's new:
--   * billing_customers       - 1:1 client ↔ Stripe customer
--   * subscriptions           - Stripe subscription mirror
--   * invoices                - Stripe invoice mirror (cents, line items)
--   * invoice_line_items      - per-line detail (promoted from jsonb)
--   * products                - Stripe product + price mirror
--   * stripe_events           - webhook idempotency + audit log
--   * apnosh_invoice_seq      - numeric sequence backing APNOSH-YYYY-NNNN
-- ============================================================

-- ──────────────────────────────────────────────────────────────
-- 1. Drop legacy billing tables (confirmed empty; check-based billing)
-- ──────────────────────────────────────────────────────────────

-- These had business_id FKs and numeric money. No live Stripe data.
drop trigger if exists set_invoice_number on invoices;
drop function if exists generate_invoice_number();
drop table if exists invoices cascade;
drop table if exists subscriptions cascade;


-- ──────────────────────────────────────────────────────────────
-- 2. billing_customers -- one Stripe customer per client
-- ──────────────────────────────────────────────────────────────
-- Narrow mirror of the Stripe customer. Contract/retainer metadata
-- continues to live on client_billing; this table is strictly about
-- the Stripe link + card-on-file visibility.

create table billing_customers (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade unique,
  stripe_customer_id text unique not null,
  default_payment_method_id text,
  payment_method_brand text,
  payment_method_last4 text,
  default_currency text default 'usd',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_billing_customers_client on billing_customers(client_id);
create index idx_billing_customers_stripe on billing_customers(stripe_customer_id);


-- ──────────────────────────────────────────────────────────────
-- 3. subscriptions -- Stripe subscription mirror
-- ──────────────────────────────────────────────────────────────

create table subscriptions (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  stripe_subscription_id text unique not null,
  stripe_customer_id text not null,
  stripe_price_id text,

  -- Denormalized for fast listing and reporting
  plan_name text not null,          -- 'Monthly Retainer (Apnosh)' etc.
  amount_cents int not null,
  currency text not null default 'usd',
  interval text not null default 'month' check (interval in ('day','week','month','year')),

  -- Stripe lifecycle mirror
  status text not null check (status in (
    'active', 'past_due', 'canceled', 'trialing', 'unpaid',
    'paused', 'incomplete', 'incomplete_expired'
  )),
  collection_method text not null default 'send_invoice' check (
    collection_method in ('send_invoice', 'charge_automatically')
  ),
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  canceled_at timestamptz,
  trial_end timestamptz,

  -- Free-form notes set by admin
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_subscriptions_client on subscriptions(client_id);
create index idx_subscriptions_stripe on subscriptions(stripe_subscription_id);
create index idx_subscriptions_status on subscriptions(status);


-- ──────────────────────────────────────────────────────────────
-- 4. Invoice numbering: APNOSH-YYYY-NNNN (continuous, never resets)
-- ──────────────────────────────────────────────────────────────

create sequence if not exists apnosh_invoice_seq start 1 increment 1;

create or replace function generate_apnosh_invoice_number()
returns text
language sql
as $$
  select 'APNOSH-' || to_char(now(), 'YYYY') || '-' || lpad(nextval('apnosh_invoice_seq')::text, 4, '0')
$$;


-- ──────────────────────────────────────────────────────────────
-- 5. invoices -- all invoices, subscription + one-time
-- ──────────────────────────────────────────────────────────────

create table invoices (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  stripe_invoice_id text unique,
  stripe_subscription_id text,       -- null for one-time invoices

  -- Human-readable identifier. Auto-generated by default.
  invoice_number text not null unique default generate_apnosh_invoice_number(),

  type text not null check (type in ('subscription', 'one_time')),
  status text not null check (status in (
    'draft', 'open', 'paid', 'void', 'uncollectible', 'failed'
  )),

  -- Money fields are ALL cents, ALL the time
  amount_due_cents int not null default 0,
  amount_paid_cents int not null default 0,
  subtotal_cents int not null default 0,
  tax_cents int not null default 0,
  total_cents int not null default 0,
  currency text not null default 'usd',

  -- Timing
  issued_at timestamptz,
  due_at timestamptz,
  paid_at timestamptz,
  voided_at timestamptz,
  period_start timestamptz,
  period_end timestamptz,

  -- Stripe-hosted surfaces
  hosted_invoice_url text,
  invoice_pdf_url text,

  -- Admin free-form
  description text,
  notes text,

  -- How payment was collected (for offline/check reconciliation)
  payment_method text,               -- 'card', 'ach', 'check', 'cash', etc.

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_invoices_client on invoices(client_id);
create index idx_invoices_stripe on invoices(stripe_invoice_id);
create index idx_invoices_subscription on invoices(stripe_subscription_id);
create index idx_invoices_status on invoices(status);
create index idx_invoices_issued on invoices(issued_at desc);


-- ──────────────────────────────────────────────────────────────
-- 6. products -- Stripe product + price mirror
-- ──────────────────────────────────────────────────────────────
-- Seeded by scripts/sync-stripe-products.ts. The 4 video products and
-- the "Monthly Retainer" umbrella product all live here.

create table products (
  id uuid primary key default gen_random_uuid(),
  stripe_product_id text unique not null,
  stripe_price_id text unique,       -- null for products with per-customer prices

  name text not null,
  description text,
  category text not null check (category in (
    'retainer', 'reel', 'website', 'gbp', 'addon', 'custom'
  )),
  billing_type text not null check (billing_type in ('recurring', 'one_time', 'variable')),

  -- Null amount means 'price determined at subscription creation'
  amount_cents int,
  currency text not null default 'usd',
  interval text check (interval in ('day','week','month','year') or interval is null),

  active boolean not null default true,
  stripe_metadata jsonb not null default '{}',

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_products_category on products(category);
create index idx_products_active on products(active);


-- ──────────────────────────────────────────────────────────────
-- 7. invoice_line_items -- line-level detail (created after products
-- so the FK resolves cleanly).
-- ──────────────────────────────────────────────────────────────

create table invoice_line_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references invoices(id) on delete cascade,
  stripe_line_item_id text,
  stripe_price_id text,
  product_id uuid references products(id) on delete set null,

  description text not null,
  quantity int not null default 1,
  unit_amount_cents int not null,
  amount_cents int not null,
  service_category text check (service_category in (
    'retainer', 'reel', 'website', 'gbp', 'addon', 'custom'
  )),

  -- For subscription line items, the billing period this covers
  period_start timestamptz,
  period_end timestamptz,

  created_at timestamptz not null default now()
);

create index idx_invoice_line_items_invoice on invoice_line_items(invoice_id);


-- ──────────────────────────────────────────────────────────────
-- 8. stripe_events -- webhook idempotency + audit log
-- ──────────────────────────────────────────────────────────────
-- The old webhook had no idempotency. Stripe retries failed webhooks;
-- processing twice double-posts work briefs, notifications, etc.
-- Every incoming event gets logged here and checked before its
-- handler runs.

create table stripe_events (
  id uuid primary key default gen_random_uuid(),
  stripe_event_id text unique not null,
  event_type text not null,
  processed_at timestamptz,
  error_message text,
  payload jsonb,
  created_at timestamptz not null default now()
);

create index idx_stripe_events_type on stripe_events(event_type);
create index idx_stripe_events_processed on stripe_events(processed_at);


-- ──────────────────────────────────────────────────────────────
-- 9. updated_at triggers
-- ──────────────────────────────────────────────────────────────
-- The set_updated_at() function was created in migration 001.

create trigger billing_customers_updated_at
  before update on billing_customers
  for each row execute function set_updated_at();

create trigger subscriptions_updated_at_v2
  before update on subscriptions
  for each row execute function set_updated_at();

create trigger invoices_updated_at_v2
  before update on invoices
  for each row execute function set_updated_at();

create trigger products_updated_at
  before update on products
  for each row execute function set_updated_at();


-- ──────────────────────────────────────────────────────────────
-- 10. Row-Level Security
-- ──────────────────────────────────────────────────────────────
-- Admin role (service role & admin profiles) has full access via
-- Supabase's bypass. Client-side reads are scoped to their client_id
-- via client_users bridge.

alter table billing_customers enable row level security;
alter table subscriptions enable row level security;
alter table invoices enable row level security;
alter table invoice_line_items enable row level security;
alter table products enable row level security;
alter table stripe_events enable row level security;

-- Products are globally readable by any authenticated user
-- (they're catalog entries, not client-specific).
create policy "products readable by authenticated"
  on products for select
  to authenticated
  using (true);

-- Stripe events are admin-only; service role bypasses RLS so this
-- effectively locks out the client side.
create policy "stripe_events admin only"
  on stripe_events for all
  to authenticated
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid()
        and profiles.role = 'admin'
    )
  );

-- Client-scoped read access via the client_users bridge.
-- (Admins bypass via service role and via the admin profile check in app code.)
create policy "client reads own billing_customer"
  on billing_customers for select
  to authenticated
  using (
    client_id in (
      select client_id from client_users
      where auth_user_id = auth.uid()
    )
  );

create policy "client reads own subscriptions"
  on subscriptions for select
  to authenticated
  using (
    client_id in (
      select client_id from client_users
      where auth_user_id = auth.uid()
    )
  );

create policy "client reads own invoices"
  on invoices for select
  to authenticated
  using (
    client_id in (
      select client_id from client_users
      where auth_user_id = auth.uid()
    )
  );

create policy "client reads own invoice line items"
  on invoice_line_items for select
  to authenticated
  using (
    invoice_id in (
      select id from invoices
      where client_id in (
        select client_id from client_users
        where auth_user_id = auth.uid()
      )
    )
  );

-- Admin full-access policies (profiles.role = 'admin').
-- Service role bypasses RLS entirely, so these are for admin clients
-- using the browser-side supabase client with their auth session.
create policy "admin full access on billing_customers"
  on billing_customers for all
  to authenticated
  using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "admin full access on subscriptions"
  on subscriptions for all
  to authenticated
  using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "admin full access on invoices"
  on invoices for all
  to authenticated
  using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "admin full access on invoice_line_items"
  on invoice_line_items for all
  to authenticated
  using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );

create policy "admin full access on products"
  on products for all
  to authenticated
  using (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  )
  with check (
    exists (select 1 from profiles where id = auth.uid() and role = 'admin')
  );


-- ──────────────────────────────────────────────────────────────
-- Done. Apply via: supabase db push (or run in SQL editor).
-- After applying, run: npm run sync-stripe-products
-- ──────────────────────────────────────────────────────────────
