-- 081_bespoke_sites.sql
-- Bespoke tier: Claude generates a complete custom-coded site (HTML+CSS)
-- per client. Stored as a string and served directly. Maximum design
-- freedom — the trade-off vs. the schema-driven Site Builder is less
-- form-based editing, but you can re-generate or tweak via prompts.

create table if not exists bespoke_sites (
  client_id uuid primary key references clients(id) on delete cascade,

  -- The generated artifacts
  html_doc text,                 -- full <!DOCTYPE html>... document
  reference_urls text[],         -- screenshots / inspiration URLs used
  brief text,                    -- the operator's design brief

  -- Generation metadata
  model text,
  prompt_tokens integer,
  completion_tokens integer,
  generation_ms integer,
  generation_id uuid references ai_generations(id) on delete set null,

  -- Versioning
  version integer not null default 1,
  generated_at timestamptz not null default now(),
  generated_by uuid references auth.users(id) on delete set null,
  notes text
);

create index if not exists bespoke_sites_generated_idx on bespoke_sites(generated_at desc);

-- Append-only history table for revert + comparison
create table if not exists bespoke_history (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references clients(id) on delete cascade,
  html_doc text,
  brief text,
  reference_urls text[],
  model text,
  version integer not null,
  generated_at timestamptz not null default now(),
  generated_by uuid references auth.users(id) on delete set null,
  notes text
);

create index if not exists bespoke_history_client_idx on bespoke_history(client_id, generated_at desc);

comment on table bespoke_sites is
  'Bespoke tier: full custom HTML+CSS sites generated by Claude. One row per client (current version); history in bespoke_history.';

-- RLS: admin only
alter table bespoke_sites enable row level security;
alter table bespoke_history enable row level security;

drop policy if exists "bespoke_sites: admin all" on bespoke_sites;
create policy "bespoke_sites: admin all" on bespoke_sites
  for all
  using (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'admin'))
  with check (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'admin'));

drop policy if exists "bespoke_history: admin read" on bespoke_history;
create policy "bespoke_history: admin read" on bespoke_history
  for select
  using (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'admin'));
