-- goal-plays-new-goals.sql
--
-- Adds the four goals the catalog does not tag yet: bigger checks, catering and private events,
-- own your takeout, and get known around here. Between them they give a door to eleven services
-- that are already built, priced and deliverable but that no goal could previously ask for.
--
-- Apply in the Supabase Dashboard SQL editor (not the CLI — db push would re-run every migration),
-- then republish the catalog:  npx tsx scripts/gen-catalog.ts
-- Then delete the `pending` arrays in src/lib/campaigns/data/plan-goals.ts; the derivation will
-- already be returning these exact ids and priorities.
--
-- Idempotent: each statement skips a service that already carries the goal.
-- Generated by scripts/tmp/gen-goal-sql.ts from PLAN_GOALS — do not hand-edit.

-- Bigger checks (bigger-checks)
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"bigger-checks","role":"Engineer the menu so guests trade up: pairings, add-ons, high-margin features.","stage":"reason","weight":9,"minTier":"standard"}]'::jsonb
  where id = 'menu-eng' and not (goal_plays @> '[{"goal":"bigger-checks"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"bigger-checks","role":"Design the offer math so a bump in spend does not come out of your margin.","stage":"easy","weight":8,"minTier":"standard"}]'::jsonb
  where id = 'incentive-design' and not (goal_plays @> '[{"goal":"bigger-checks"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"bigger-checks","role":"Shoot the high-margin items properly, because people order what looks best.","stage":"reason","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'photo-library' and not (goal_plays @> '[{"goal":"bigger-checks"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"bigger-checks","role":"Put the items you want ordered where they get seen and read.","stage":"easy","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'site-menu' and not (goal_plays @> '[{"goal":"bigger-checks"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"bigger-checks","role":"Measure spend per guest, so you can tell whether any of this moved it.","stage":"backstage","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'tracking' and not (goal_plays @> '[{"goal":"bigger-checks"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"bigger-checks","role":"Monthly read on average check and which items are actually carrying it.","stage":"backstage","weight":4,"minTier":"standard"}]'::jsonb
  where id = 'reporting' and not (goal_plays @> '[{"goal":"bigger-checks"}]'::jsonb);

-- Catering and parties (catering)
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"catering","role":"The whole catering side: package, pricing, enquiry form and the follow-up.","stage":"reason","weight":9,"minTier":"standard"}]'::jsonb
  where id = 'catering-engine' and not (goal_plays @> '[{"goal":"catering"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"catering","role":"A real catering page so an office planner can see what they get and ask.","stage":"easy","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'site-menu' and not (goal_plays @> '[{"goal":"catering"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"catering","role":"Photos of platters, big tables and the private room, which is what gets booked.","stage":"reason","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'photo-library' and not (goal_plays @> '[{"goal":"catering"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"catering","role":"Count enquiries and bookings, so you know what the catering side is worth.","stage":"backstage","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'tracking' and not (goal_plays @> '[{"goal":"catering"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"catering","role":"Designed promo for the catering offer, ready for anywhere you post it.","stage":"found","weight":6,"minTier":"standard"}]'::jsonb
  where id = 'graphic' and not (goal_plays @> '[{"goal":"catering"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"catering","role":"A Facebook event page for the private nights you want filled.","stage":"found","weight":5,"minTier":"standard"}]'::jsonb
  where id = 'fb-event' and not (goal_plays @> '[{"goal":"catering"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"catering","role":"Get found for the catering searches happening near you right now.","stage":"found","weight":7,"minTier":"standard"}]'::jsonb
  where id = 'local-seo' and not (goal_plays @> '[{"goal":"catering"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"catering","role":"Keep the catering offer visible on your Google profile all month.","stage":"found","weight":4,"minTier":"standard"}]'::jsonb
  where id = 'gbp-posts' and not (goal_plays @> '[{"goal":"catering"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"catering","role":"Keep the private-events side alive on your social pages, not just the menu.","stage":"found","weight":3,"minTier":"standard"}]'::jsonb
  where id = 'social-mgmt' and not (goal_plays @> '[{"goal":"catering"}]'::jsonb);

-- Own your takeout (own-takeout)
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"own-takeout","role":"Order and book on your own site, so you keep the guest and the margin.","stage":"easy","weight":9,"minTier":"standard"}]'::jsonb
  where id = 'ordering-setup' and not (goal_plays @> '[{"goal":"own-takeout"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"own-takeout","role":"A fast, readable menu page that converts a hungry visitor into an order.","stage":"easy","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'site-menu' and not (goal_plays @> '[{"goal":"own-takeout"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"own-takeout","role":"Photos on your own ordering page, the thing that lifts a basket.","stage":"reason","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'photo-library' and not (goal_plays @> '[{"goal":"own-takeout"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"own-takeout","role":"Measure direct orders against app orders, so the shift is visible.","stage":"backstage","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'tracking' and not (goal_plays @> '[{"goal":"own-takeout"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"own-takeout","role":"Keep the site and menu current, because a stale page sends them back to the app.","stage":"easy","weight":6,"minTier":"standard"}]'::jsonb
  where id = 'website-care' and not (goal_plays @> '[{"goal":"own-takeout"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"own-takeout","role":"Point the Order button on Google at your own site, not the delivery apps.","stage":"found","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'gbp-setup' and not (goal_plays @> '[{"goal":"own-takeout"}]'::jsonb);

-- Get known around here (get-known)
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"get-known","role":"A consistent look and voice, so everything you put out reads as one place.","stage":"reason","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'brand-kit' and not (goal_plays @> '[{"goal":"get-known"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"get-known","role":"Pitch your story to local writers, lists and guides.","stage":"found","weight":8,"minTier":"standard"}]'::jsonb
  where id = 'pr-media' and not (goal_plays @> '[{"goal":"get-known"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"get-known","role":"A dedicated shoot for the piece you actually want people to see.","stage":"found","weight":7,"minTier":"standard"}]'::jsonb
  where id = 'video-single' and not (goal_plays @> '[{"goal":"get-known"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"get-known","role":"Keep your pages active, which is where most people check you out first.","stage":"found","weight":9,"minTier":"standard"}]'::jsonb
  where id = 'social-mgmt' and not (goal_plays @> '[{"goal":"get-known"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"get-known","role":"The image library everything else draws from.","stage":"reason","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'photo-library' and not (goal_plays @> '[{"goal":"get-known"}]'::jsonb);
update catalog_services set goal_plays = coalesce(goal_plays, '[]'::jsonb) || '[{"goal":"get-known","role":"Measure whether any of it turned into people looking you up.","stage":"backstage","weight":3,"minTier":"lean"}]'::jsonb
  where id = 'tracking' and not (goal_plays @> '[{"goal":"get-known"}]'::jsonb);

-- verify: every new goal should report the expected service count
select p->>'goal' as goal, count(*) as services
from catalog_services, jsonb_array_elements(goal_plays) p
where p->>'goal' in ('bigger-checks','catering','own-takeout','get-known')
group by 1 order by 1;
